
version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/RIDEDM

permissions:
- object: /RIDEDM/appspec.yml
  pattern: "**"
  owner: ubuntu
  group: ubuntu
  exclude: true

hooks:
  # During the BeforeInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  BeforeInstall:
    - location: client/scripts/before_install.sh
      timeout: 1600
      runas: root
  # During the AfterInstall deployment lifecycle event, run the commands
  #   in the script specified in "location".
  AfterInstall:
    - location: client/scripts/after_install.sh
      timeout: 1600
      runas: root

  # During the ApplicationStart deployment lifecycle event, run the commands
  #   in the script specified in "location".
  ApplicationStart:
    - location: client/scripts/app_start.sh
      timeout: 300
      runas: root

