version: 0.2
phases:
  pre_build:
    commands:
      - cd client
      - npm install
      - npm install react-scripts
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - client/**/*
    - api/**/*
    - socket/**/*
    - scripts/**/*
    - appspec.yml

