version: 0.2
phases:
  pre_build:
    commands:
      - cd /var/www/html/RIDEDM # Change directory to the Git repository
      - git pull  # Update the repository with the latest changes
      - cd client
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - client/public/**/*
    - client/src/**/*
    - client/package.json
    - appspec.yml
    - client/scripts/**/*
